---
development:
  cloud_name: taskmanagerspa
  api_key: '731985237662856'
  api_secret: "-ERApeJFqnjrd16E0eWk5weDmls"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: taskmanagerspa
  api_key: '731985237662856'
  api_secret: "-ERApeJFqnjrd16E0eWk5weDmls"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: taskmanagerspa
  api_key: '731985237662856'
  api_secret: "-ERApeJFqnjrd16E0eWk5weDmls"
  enhance_image_tag: true
  static_image_support: false